### ISSUE TITLE
CSV from Mac does not work

### ISSUE THREAD

**Issue by corinnaglasner** [phylocanvas/phylocanvas.github.io#10]
If a user saves a csv file on a Mac, it does not work. Only if it is saved as Windows or MS-DOS Comma Separated not if you save it as the Mac .csv. As this version inserts ^M into the file.

**Comment by richardgoater** [comment]
@corinnaglasner please can you confirm that this is now fixed?

**Comment by richardgoater** [comment]
confirmed fixed by @corinnaglasner.
